media:
  input: src/images
  output: ""
content:
  - name: projects
    label: Projects
    path: src/content/student_projects
    type: collection
    view:
      fields: [ visible, title ]
      primary: title
      sort: [ visible, title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: type
        label: Type
        type: string
      - name: visible
        label: Visible
        type: boolean
        default: true
      - name: image
        label: Image
        type: image
      - name: body
        label: Description
        type: code
        options:
          language: markdown
  - name: lectures
    label: Lectures
    path: src/content/lectures
    type: collection
    view:
      fields: [ title ]
      primary: title
      sort: [ title ]
    fields:
      - name: title
        label: Title
        type: string
      - name: lecture
        label: Lecture Key
        type: string
      - name: summary
        label: Summary
        type: string
      - name: body
        label: Description
        type: code
        options:
          language: markdown
  - name: news
    label: News
    path: src/content/news.yaml
    type: file
    format: raw
  - name: team
    label: Team
    path: src/content/team.yaml
    type: file
    format: raw
  - name: opportunities
    label: Opportunitues
    path: src/content/opportunities.md
    type: file
